### ISSUE TITLE
 🐛 [BugReport] PayloadTooLargeError: request entity too large in production

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Human-Connection#3036]
## :bug: Bugreport

We are getting these errors in our `production` backend node 
```
2020-02-09T22:40:51.326143236Z PayloadTooLargeError: request entity too large
2020-02-09T22:40:51.326200669Z     at readStream (/nitro-backend/node_modules/raw-body/index.js:155:17)
2020-02-09T22:40:51.326208151Z     at getRawBody (/nitro-backend/node_modules/raw-body/index.js:108:12)
2020-02-09T22:40:51.326212452Z     at read (/nitro-backend/node_modules/body-parser/lib/read.js:77:3)
2020-02-09T22:40:51.326216017Z     at jsonParser (/nitro-backend/node_modules/body-parser/lib/types/json.js:135:5)
2020-02-09T22:40:51.326219981Z     at Layer.handle [as handle_request] (/nitro-backend/node_modules/express/lib/router/layer.js:95:5)
2020-02-09T22:40:51.326224074Z     at trim_prefix (/nitro-backend/node_modules/express/lib/router/index.js:317:13)
2020-02-09T22:40:51.326228183Z     at /nitro-backend/node_modules/express/lib/router/index.js:284:7
2020-02-09T22:40:51.326231988Z     at Function.process_params (/nitro-backend/node_modules/express/lib/router/index.js:335:12)
2020-02-09T22:40:51.32623616Z     at next (/nitro-backend/node_modules/express/lib/router/index.js:275:10)
2020-02-09T22:40:51.326240191Z     at cors (/nitro-backend/node_modules/cors/lib/index.js:188:7)

```
We also have had the backend restart 2 in the last 5 days, unsure if this is somehow related.
### Steps to reproduce the behavior
1. check backend logs(requires cluster management rights in kubernetes)
2. see the logs
3. Profit

### Expected behavior

should we increase the `nginx.ingress.kubernetes.io/proxy-body-size`? If so, what is a reasonable size?

### Version & Environment
 Type: []      
 - OS: []      
 - Browser: [] 
 - Version []  
 - Device: []  

### Additional context

At the moment, we have this set to `10m`

**Comment by mattwr18** [comment]
potential fix:
```
const bodyParser = require('body-parser');

// Tell the bodyparser middleware to accept more data
app.use(bodyParser.json({limit: '50mb'}));
app.use(bodyParser.urlencoded({limit: '50mb', extended: true}));
```
from this closed issue :point_down:
https://github.com/expressjs/body-parser/issues/235#issuecomment-405013415
