### ISSUE TITLE
Flaky Cucumber Tests

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#338]
**Describe the bug**
Our build server fails from time to time on a particular cucumber feature "Tags and Categories" with a time out. Another flaky test is "moderation/ReportContent.feature".

**To Reproduce**
This is a hard-to-reproduce bug.

**Expected behavior**
Build server is passing.

**Screenshots**
![Screenshot_48](https://user-images.githubusercontent.com/2110676/55335716-f050c500-549b-11e9-9273-9520416227a9.png)

**Additional Context**
Log output of TagsAndCategories:
```
  1 passing (25s)
  1 failing
  1) Tags and Categories See an overview of tags:
     CypressError: Timed out retrying: expected '<td.ds-table-col>' to contain 'Ecology'
      at Object.cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:65727:11)
      at Object.throwErr (http://localhost:3000/__cypress/runner/cypress_runner.js:65692:18)
      at Object.throwErrByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:65719:17)
      at retry (http://localhost:3000/__cypress/runner/cypress_runner.js:59237:16)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:51312:18
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:131273:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:129291:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:129348:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:129393:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:129468:18)
      at Async._drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:126197:16)
      at Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:126207:10)
      at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:126081:14)

```

This is the log output of the failing moderation cypress test:
```
  Report and Moderate
    ✓ Report a post from various pages (example #1) (7148ms)
    ✓ Report a post from various pages (example #2) (6092ms)
    1) Report user
    ✓ Review reported content (5696ms)
    ✓ Normal user can't see the moderation page (3953ms)
  4 passing (32s)
  1 failing
  1) Report and Moderate Report user:
     CypressError: Timed out retrying: cy.click() failed because this element is not visible:
<button class="ds-button content-menu-trigger ds-button-size-small ds-button-ghost">...</button>
This element '<button.ds-button.content-menu-trigger.ds-button-size-small.ds-button-ghost>' is not visible because it has an effective width and height of: '0 x 0' pixels.
Fix this problem, or use {force: true} to disable error checking.
https://on.cypress.io/element-cannot-be-interacted-with
      at Object.cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:65727:11)
      at Object.throwErr (http://localhost:3000/__cypress/runner/cypress_runner.js:65692:18)
      at Object.throwErrByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:65719:17)
      at Object.retry (http://localhost:3000/__cypress/runner/cypress_runner.js:59237:16)
      at retryActionability (http://localhost:3000/__cypress/runner/cypress_runner.js:50983:19)
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:131273:23)
      at Function.Promise.attempt.Promise.try (http://localhost:3000/__cypress/runner/cypress_runner.js:128647:29)
      at tryFn (http://localhost:3000/__cypress/runner/cypress_runner.js:59473:24)
      at whenStable (http://localhost:3000/__cypress/runner/cypress_runner.js:59501:12)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:59261:16
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:131273:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:129291:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:129348:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:129393:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:129472:18)
      at Promise._fulfill (http://localhost:3000/__cypress/runner/cypress_runner.js:129417:18)
```
![Screenshot (58)](https://user-images.githubusercontent.com/2110676/55345342-f0f35680-54af-11e9-9e5a-614d05aab610.png)
![Screenshot (57)](https://user-images.githubusercontent.com/2110676/55345346-f3ee4700-54af-11e9-907e-f870f7883644.png)

**Comment by roschaefer** [comment]
@ulfgebhardt your PR #339 failed because of this flaky test. I updated the issue.

**Comment by mattwr18** [comment]
something that helped me on a different project was to use `cy.click({ force: true })`

see this issue https://github.com/cypress-io/cypress/issues/695

**Comment by roschaefer** [comment]
@mattwr18 thanks for the tip.

@ulfgebhardt Since this is a blocker I decided to put it in milestone [Hera](https://github.com/Human-Connection/Human-Connection/milestone/13).
